install.packages("dplyr")
Dataframe <- read.csv("C:/Users/umar_/OneDrive/Desktop/R Analysis/MechaCar_mpg.csv")
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=Dataframe)
model <- (lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=Dataframe))
summary(model)
Table <- read.csv("C:/Users/umar_/OneDrive/Desktop/R Analysis/Suspension_Coil.csv")
total_summary <- Table %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI),)
lot_summary <- Table %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI), .groups = 'keep')
sample_table <- Table %>% sample_n(150)
t.test((sample_table$PSI),mu=1500)
Sample_manufacturing_lot1 <- subset(sample_table, Manufacturing_Lot == "Lot1")
t.test((Sample_manufacturing_lot1$PSI),mu=1500)
Sample_manufacturing_lot2 <- subset(sample_table, Manufacturing_Lot == "Lot2")
t.test((Sample_manufacturing_lot2$PSI),mu=1500)
Sample_manufacturing_lot3 <- subset(sample_table, Manufacturing_Lot == "Lot3")
t.test((Sample_manufacturing_lot3$PSI),mu=1500)